#!/bin/bash

cd ./extension

glib-compile-schemas schemas/

gnome-extensions pack --force\
                      --podir=locale ./\
                      --schema schemas/gschemas.compiled \
                      --extra-source ../LICENSE\
                      --extra-source assets/\
                      --extra-source ui/\
                      --extra-source services/\
                      --extra-source utils/\
                      --extra-source shell/\
                      --extra-source settings/\
                      --out-dir ../

rm schemas/gschemas.compiled
